import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import AdminUserSync from './components/AdminUserSync.jsx'
import Home from './pages/home/Home.jsx'
import Pets from './pages/pets/Pets.jsx'
import PetDetail from './pages/pets/PetDetail.jsx'
import Recommendation from './pages/recommendation/Recommendation.jsx'
import Products from './pages/products/Products.jsx'
import ProductDetail from './pages/product-detail/ProductDetail.jsx'
import Cart from './pages/cart/Cart.jsx'
import Checkout from './pages/cart/Checkout.jsx'
import OrderSuccess from './pages/cart/OrderSuccess.jsx'
import Orders from './pages/orders/Orders.jsx'
import OrderDetail from './pages/orders/OrderDetail.jsx'
import Profile from './pages/profile/Profile.jsx'
import ProfileSettings from './pages/profile/ProfileSettings.jsx'
import EditProfile from './pages/profile/EditProfile.jsx'
import Help from './pages/profile/Help.jsx'
import Coupons from './pages/profile/Coupons.jsx'
import Favorites from './pages/profile/Favorites.jsx'
import Notifications from './pages/notifications/Notifications.jsx'
import AdminRoute from './pages/admin/AdminRoute.jsx'
import AdminLogin from './pages/admin/AdminLogin.jsx'
import AdminLayout from './pages/admin/AdminLayout.jsx'
import AdminDashboard from './pages/admin/AdminDashboard.jsx'
import AdminOrders from './pages/admin/AdminOrders.jsx'
import AdminOrderDetail from './pages/admin/AdminOrderDetail.jsx'
import AdminProducts from './pages/admin/AdminProducts.jsx'
import AdminCustomers from './pages/admin/AdminCustomers.jsx'
import AdminCustomerDetail from './pages/admin/AdminCustomerDetail.jsx'
import AdminCoupons from './pages/admin/AdminCoupons.jsx'
import AdminNotifications from './pages/admin/AdminNotifications.jsx'
import AdminSettings from './pages/admin/AdminSettings.jsx'
import AdminReports from './pages/admin/AdminReports.jsx'
import AdminStore from './pages/admin/AdminStore.jsx'
import Login from './pages/Login.jsx'

export default function App(){return <BrowserRouter><AdminUserSync/><Routes>
<Route path="/" element={<Navigate to="/login" replace/>}/><Route path="/login" element={<Login/>}/><Route path="/home" element={<Home/>}/><Route path="/pets" element={<Pets/>}/><Route path="/pets/:petId" element={<PetDetail/>}/><Route path="/recommendation" element={<Recommendation/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:productId" element={<ProductDetail/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/orders/success" element={<OrderSuccess/>}/><Route path="/orders/:orderId" element={<OrderDetail/>}/><Route path="/orders" element={<Orders/>}/><Route path="/profile" element={<Profile/>}/><Route path="/profile/edit" element={<EditProfile/>}/><Route path="/profile/addresses" element={<ProfileSettings type="addresses"/>}/><Route path="/profile/payment" element={<ProfileSettings type="payment"/>}/><Route path="/profile/favorites" element={<Favorites/>}/><Route path="/profile/coupons" element={<Coupons/>}/><Route path="/profile/help" element={<Help/>}/><Route path="/notifications" element={<Notifications/>}/><Route path="/home/admin/login" element={<AdminLogin/>}/><Route path="/home/admin" element={<AdminRoute><AdminLayout/></AdminRoute>}><Route index element={<AdminDashboard/>}/><Route path="orders" element={<AdminOrders/>}/><Route path="orders/:orderId" element={<AdminOrderDetail/>}/><Route path="products" element={<AdminProducts/>}/><Route path="customers" element={<AdminCustomers/>}/><Route path="customers/:userId" element={<AdminCustomerDetail/>}/><Route path="coupons" element={<AdminCoupons/>}/><Route path="notifications" element={<AdminNotifications/>}/><Route path="reports" element={<AdminReports/>}/><Route path="store" element={<AdminStore/>}/><Route path="settings" element={<AdminSettings/>}/></Route>
<Route path="*" element={<Navigate to="/home" replace/>}/></Routes></BrowserRouter>}
