import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { loadAdminData, updateAdminData } from '../../admin/data'
import { restoreOrderStock, notifyOrderStatusChanged } from '../../admin/commerce.js'

const statuses=['รอดำเนินการ','กำลังจัดส่ง','จัดส่งแล้ว','สำเร็จ','ยกเลิก']
const statusTone={ 'รอดำเนินการ':'bg-violet-50 text-violet-600','กำลังจัดส่ง':'bg-blue-50 text-blue-600','จัดส่งแล้ว':'bg-emerald-50 text-emerald-600','สำเร็จ':'bg-green-50 text-green-700','ยกเลิก':'bg-red-50 text-red-500' }

export default function AdminOrderDetail(){
  const {orderId}=useParams(); const navigate=useNavigate()
  const [order,setOrder]=useState(null); const [editing,setEditing]=useState(false); const [confirmCancel,setConfirmCancel]=useState(false); const [form,setForm]=useState({status:'รอดำเนินการ',payment:'รอตรวจสอบ',shipping:'ยังไม่จัดส่ง',tracking:''}); const [toast,setToast]=useState('')
  const refresh=()=>{const id=decodeURIComponent(orderId||''); const found=(loadAdminData().orders||[]).find(o=>String(o.id)===id); if(found){setOrder(found);setForm({status:found.status||'รอดำเนินการ',payment:found.payment||'รอตรวจสอบ',shipping:found.shipping||'ยังไม่จัดส่ง',tracking:found.tracking || (String(found.shipping||'').startsWith('TH') ? found.shipping : '')})}}
  useEffect(()=>{refresh();window.addEventListener('petshop-admin-data-updated',refresh);return()=>window.removeEventListener('petshop-admin-data-updated',refresh)},[orderId])
  const items=order?.items||order?.products||[]; const subtotal=useMemo(()=>items.reduce((s,i)=>s+Number(i.price||0)*Number(i.qty||1),0),[items])
  if(!order)return <div className="rounded-xl border border-[#ececf2] bg-white p-12 text-center"><p className="text-sm font-bold">ไม่พบคำสั่งซื้อ</p><button onClick={()=>navigate('/home/admin/orders')} className="mt-4 rounded-lg bg-[#6d3df5] px-4 py-2 text-xs font-bold text-white">กลับรายการคำสั่งซื้อ</button></div>
  const save=()=>{const previousStatus=order.status; const previousPayment=order.payment; const nextOrder={...order,...form,shipping:form.tracking ? form.tracking : form.shipping}; if(form.status==='ยกเลิก' && previousStatus!=='ยกเลิก'){restoreOrderStock(nextOrder)} updateAdminData(data=>{const x=data.orders.find(o=>String(o.id)===String(order.id));if(x)Object.assign(x,{...form,shipping:form.tracking ? form.tracking : form.shipping,stockRestored:form.status==='ยกเลิก'?true:x.stockRestored})}); notifyOrderStatusChanged(nextOrder, previousStatus, previousPayment); setEditing(false);setConfirmCancel(false);setToast('บันทึกข้อมูลคำสั่งซื้อแล้ว');setTimeout(()=>setToast(''),2200)}
  const requestSave=()=>{if(form.status==='ยกเลิก' && order.status!=='ยกเลิก'){setConfirmCancel(true);return} save()}
  return <div className="space-y-4 pb-20 md:pb-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><div className="text-[10px] text-gray-400"><Link to="/home/admin">หน้าหลัก</Link><i className="fa-solid fa-chevron-right mx-2 text-[8px]"/><Link to="/home/admin/orders">คำสั่งซื้อ</Link><i className="fa-solid fa-chevron-right mx-2 text-[8px]"/>รายละเอียด</div><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="truncate text-[20px] font-extrabold sm:text-[22px]">{order.id}</h1><span className={`shrink-0 rounded-full px-2.5 py-1 text-[9px] font-bold ${statusTone[order.status]||'bg-gray-50 text-gray-500'}`}>{order.status}</span></div><p className="mt-0.5 text-[10px] text-gray-400">สั่งซื้อเมื่อ {order.date||'24 พ.ค. 68'} {order.time||'14:30 น.'}</p></div><div className="grid w-full grid-cols-2 gap-2 sm:flex sm:w-auto"><button onClick={()=>window.print()} className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-[10px] font-bold text-gray-600"><i className="fa-solid fa-print mr-2"/>พิมพ์</button><button onClick={()=>setEditing(true)} className="rounded-lg bg-[#6d3df5] px-3 py-2 text-[10px] font-bold text-white"><i className="fa-solid fa-pen mr-2"/>แก้ไขสถานะ</button></div></div>
    <div className="grid gap-4 xl:grid-cols-[1.55fr_1fr]">
      <div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Info title="ข้อมูลลูกค้า" icon="fa-user"><b>{order.customer||'ไม่ระบุ'}</b><p className="mt-1 text-[11px] text-gray-500">{order.phone||'—'}</p><p className="text-[11px] text-gray-500">{order.email||'—'}</p></Info><Info title="ที่อยู่จัดส่ง" icon="fa-location-dot"><b>{order.address||'ยังไม่มีข้อมูลที่อยู่'}</b><p className="mt-1 text-[11px] text-gray-500">{order.shippingAddress||''}</p><p className="mt-1 text-[11px] text-gray-500">เลขพัสดุ: {order.tracking|| (String(order.shipping||'').startsWith('TH')?order.shipping:'ยังไม่ระบุ')}</p></Info></div>
      <section className="rounded-xl border border-[#ececf2] bg-white p-4 shadow-[0_2px_10px_rgba(30,30,50,0.03)]"><div className="flex justify-between"><h2 className="text-sm font-extrabold">รายการสินค้า</h2><span className="text-[10px] text-gray-400">{items.length||'—'} รายการ</span></div>{items.length?<div className="mt-3 divide-y divide-gray-100">{items.map((i,n)=><div key={i.id||n} className="flex items-center gap-3 py-2.5"><span className="grid size-9 place-items-center rounded-lg bg-gray-50 text-gray-400"><i className={`fa-solid ${i.icon||'fa-box'} text-[10px]`}/></span><div className="flex-1"><p className="text-[11px] font-bold">{i.name||'สินค้า'}</p><p className="text-[9px] text-gray-400">จำนวน {i.qty||1} ชิ้น</p></div><b className="text-[11px]">฿{(Number(i.price||0)*Number(i.qty||1)).toLocaleString()}</b></div>)}</div>:<p className="py-6 text-center text-[10px] text-gray-400">ยังไม่มีรายการสินค้าในข้อมูลจำลอง</p>}<div className="mt-3 space-y-1 rounded-lg bg-gray-50 p-3 text-[11px]"><div className="flex justify-between"><span className="text-gray-500">ยอดสินค้า</span><b>฿{subtotal.toLocaleString()}</b></div><div className="flex justify-between"><span className="text-gray-500">ส่วนลด</span><b className="text-emerald-600">-฿{Number(order.discount||0).toLocaleString()}</b></div><div className="flex justify-between"><span className="text-gray-500">ค่าจัดส่ง</span><b>฿{Number(order.delivery||0).toLocaleString()}</b></div><div className="mt-2 flex justify-between border-t border-gray-200 pt-2 text-sm"><b>ยอดรวม</b><b className="text-[#6d3df5]">฿{Number(order.total||0).toLocaleString()}</b></div></div></section></div>
      <div className="space-y-4"><Info title="การชำระเงิน" icon="fa-credit-card"><p className="text-[10px] text-gray-400">สถานะ</p><span className={`mt-1 inline-flex rounded-full px-2 py-1 text-[9px] font-bold ${order.payment==='ชำระแล้ว'?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}>{order.payment||'รอตรวจสอบ'}</span><p className="mt-3 text-[10px] text-gray-400">วิธีการชำระเงิน</p><b className="text-[12px]">{order.paymentMethod?.name||order.paymentMethod||'พร้อมเพย์'}</b><p className="mt-2 text-[10px] text-gray-400">ยอดที่ชำระ</p><b className="text-lg text-[#6d3df5]">฿{Number(order.total||0).toLocaleString()}</b></Info><Info title="ข้อมูลจัดส่ง" icon="fa-truck"><p className="text-[10px] text-gray-400">สถานะการจัดส่ง</p><b>{order.status}</b><p className="mt-2 text-[10px] text-gray-400">เลขพัสดุ</p><b>{order.tracking|| (String(order.shipping||'').startsWith('TH')?order.shipping:'ยังไม่ระบุ')}</b></Info><Info title="หมายเหตุ" icon="fa-note-sticky"><p className="text-[11px] text-gray-500">{order.note||'ไม่มีหมายเหตุเพิ่มเติม'}</p></Info></div>
    </div>
    {editing&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/30 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-base font-extrabold">แก้ไขคำสั่งซื้อ</h2><button onClick={()=>setEditing(false)} className="grid size-8 place-items-center rounded-lg text-gray-400 hover:bg-gray-50"><i className="fa-solid fa-xmark"/></button></div><div className="mt-4 space-y-3"><Field label="สถานะคำสั่งซื้อ"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="h-10 w-full rounded-lg border border-gray-200 px-3 text-xs">{statuses.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="การชำระเงิน"><select value={form.payment} onChange={e=>setForm({...form,payment:e.target.value})} className="h-10 w-full rounded-lg border border-gray-200 px-3 text-xs"><option>รอตรวจสอบ</option><option>ชำระแล้ว</option><option>ยกเลิก</option></select></Field><Field label="ข้อมูลจัดส่ง"><input value={form.shipping} onChange={e=>setForm({...form,shipping:e.target.value})} placeholder="เช่น ยังไม่จัดส่ง / Kerry" className="h-10 w-full rounded-lg border border-gray-200 px-3 text-xs"/></Field><Field label="เลขพัสดุ (Tracking Number)"><input value={form.tracking} onChange={e=>setForm({...form,tracking:e.target.value.toUpperCase()})} placeholder="เช่น TH123456789" className="h-10 w-full rounded-lg border border-gray-200 px-3 text-xs uppercase"/></Field></div><div className="mt-5 flex gap-2"><button onClick={()=>setEditing(false)} className="h-10 flex-1 rounded-lg border border-gray-200 text-xs font-bold text-gray-500">ยกเลิก</button><button onClick={requestSave} className="h-10 flex-1 rounded-lg bg-[#6d3df5] text-xs font-bold text-white">บันทึก</button></div></div></div>}
    {confirmCancel&&<div className="fixed inset-0 z-[110] grid place-items-center bg-gray-950/45 p-4 backdrop-blur-sm"><div className="w-full max-w-sm overflow-hidden rounded-[24px] bg-white shadow-2xl"><div className="h-1.5 bg-red-500"/><div className="p-6 text-center"><span className="mx-auto grid size-16 place-items-center rounded-full bg-red-50 text-red-500"><i className="fa-solid fa-triangle-exclamation text-xl"/></span><h2 className="mt-4 text-lg font-extrabold">ยืนยันยกเลิกคำสั่งซื้อ?</h2><p className="mt-1 text-xs text-gray-500">{order.id} · {order.customer||'ไม่ระบุลูกค้า'}</p><p className="mt-2 text-[10px] leading-4 text-red-400">เมื่อยกเลิกแล้ว ระบบจะคืนสต็อกสินค้าและแจ้งเตือนลูกค้า</p><div className="mt-6 flex gap-2"><button onClick={()=>setConfirmCancel(false)} className="h-11 flex-1 rounded-xl border border-gray-200 text-xs font-bold text-gray-500">ย้อนกลับ</button><button onClick={save} className="h-11 flex-1 rounded-xl bg-red-500 text-xs font-bold text-white hover:bg-red-600">ยืนยันยกเลิก</button></div></div></div></div>}
    {toast&&<div className="fixed inset-x-4 bottom-5 z-[120] mx-auto w-auto max-w-md rounded-xl bg-gray-900 px-4 py-3 text-center text-xs font-bold text-white shadow-xl sm:inset-x-auto sm:right-5 sm:w-auto sm:max-w-none sm:text-left"><i className="fa-solid fa-circle-check mr-2 text-emerald-400"/>{toast}</div>}
  </div>
}
function Info({title,icon,children}){return <section className="rounded-xl border border-[#ececf2] bg-white p-4 shadow-[0_2px_10px_rgba(30,30,50,0.03)]"><h2 className="mb-3 text-[11px] font-extrabold"><i className={`fa-solid ${icon} mr-2 text-[#6d3df5]`}/>{title}</h2>{children}</section>}
function Field({label,children}){return <label className="block"><span className="mb-1 block text-[10px] font-bold text-gray-500">{label}</span>{children}</label>}
